server:
  port : 8090
  servlet:
    context-path: '/account/'

spring:
  application:
    name: account
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/account?authSource=admin

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
