version: '3.2'

services:
  mongo:
    image: mongo:4.2.6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      -  pgg-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - pgg-net

volumes:
  pgg-db:

networks:
  pgg-net:
    driver: bridge